### ISSUE TITLE
Menu has an offset

### ISSUE THREAD

**Issue by mifth** [GuilhermeGSousa/game-base-2D#4]
Menu has an offset. Godot 4.2.

![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/2251298/8dc9718d-e2a6-440a-bf9f-4f26002cb23d)
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/2251298/571118c5-9cc4-43d4-b507-d8e19df28309)

**Comment by GuilhermeGSousa** [comment]
Hmm this happens because the menu is made for 1152*648 viewports. If you wish to use different ratios you'd need to set those here:
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/13313321/60342013-88c8-4772-8830-524f8a4aa60f)

For reference here's my project settings (also works in fullscreen)
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/13313321/eef13216-6b2e-494d-a653-7e038e326b63)

**Comment by mifth** [comment]
Ui should be adaptable and independent to any ratio. In other case it's buggy, I'm afraid.

**Comment by GuilhermeGSousa** [comment]
![resize](https://github.com/user-attachments/assets/d6c50910-d4b5-4805-8bb6-14dbeca43f54)

Was testing this today, resizing seems to work correctly as of latest, I'll close this issue for now.
