### ISSUE TITLE
Strange dragging.

### ISSUE THREAD

**Issue by mifth** [GuilhermeGSousa/game-base-2D#6]
Strange dragging. See my video.
[2023-10-31 22-12-28.zip](https://github.com/GuilhermeGSousa/game-base-2D/files/13221447/2023-10-31.22-12-28.zip)

**Comment by GuilhermeGSousa** [comment]
I'm wondering if this may be related to the other issue on the camera targeter you mentioned? I'll try this once that is fixed.

Also, this is unrelated to this issue, but Godot 4.2 has a bug where sometimes node paths get unset, which is why your minimap isn't working. Could you set this property:

![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/13313321/37b5d07d-8566-44ac-9c2f-3315fe40c1e5)

After that your minimap should look like this:
![image](https://github.com/GuilhermeGSousa/game-base-2D/assets/13313321/6cb5a7a5-3166-44ec-b3d6-8420e2c0badc)

**Comment by GuilhermeGSousa** [comment]
Ok this is happening because your `CameraArea` is updating the camera on `_process`. Everything that updates the camera needs to do so on the physics update. Adding that to the fixes

**Comment by mifth** [comment]
Please, let me know if I need to test anything again. Thanks a lot for fixing!
